version: '3'

x-bootnode:
  &bootnode
  - /bin/sh
  - -c
  - |
    kscn --datadir "/src" init "/init/genesis.json"
    kscn --rpc --rpcaddr "0.0.0.0" --rpcport "8551" --rpccorsdomain "*" \
    --ws --wsaddr "0.0.0.0" --wsport "9551" --wsorigins "*" --wsapi "klay,net,personal,debug,eth,txpool,admin" \
    --datadir "/src" --port "32323" --rpcapi "klay,net,personal,debug,eth,txpool,admin" --networkid "8216" \
    --nodekeyhex "871ccee7755bb4247e783110cafa6437f9f593a1eaeebe0efcc1b0852282c3e5" \
    --nodiscover --debug --keystore="/keystore" --syncmode "full" 

x-attach:
  &attach
  - /bin/sh
  - -c
  - |
    ksen --datadir "/src" init "/init/genesis.json"
    ksen --rpc --rpcaddr "0.0.0.0" --rpcport "8551" --rpccorsdomain "*" \
    --ws --wsaddr "0.0.0.0" --wsport "9551" --wsorigins "*" --wsapi "klay,net,personal,debug,eth,txpool,admin" \
    --bootnodes "enode://b299bf5bb0b5e91ddf35e055bef9b69c38112bae582b589d4ab4955f6b0f8e790a182530bd57cff00cad1eb49c39d6ab66eaaa979c5d644681ee124649c5f00f@10.111.0.2:32323" \
    --datadir "/src" --port "32323" --rpcapi "klay,net,personal,debug,eth,txpool,admin" --networkid "8216" \
    --nodiscover --debug --keystore="/keystore" --syncmode "full" 

services:
  CN:
    image: klaytn/klaytn:v0.9.2
    ports:
      - '32323:32323'
      - '8551:8551'
      - '9551:9551'
      - '61001:61001'
    entrypoint: *bootnode
    volumes:
      - ./klay-volumes:/init
      - ./klay-volumes/node1:/keystore
    restart: "always"
    networks:
      antps-klaytn-networks:
        ipv4_address: 10.111.0.2

  EN:
    image: klaytn/klaytn:v0.9.2
    ports:
      - '32324:32323'
      - '8552:8551'
      - '9552:9551'
      - '61002:61001'
    entrypoint:
      *attach
    volumes:
      - ./klay-volumes:/init
      - ./klay-volumes/node2:/keystore
    depends_on:
      - CN
    restart: "always"
    networks:
      antps-klaytn-networks:
        ipv4_address: 10.111.0.3

  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_PASSWORD: "0xantps"
      POSTGRES_DB: "antps_dev"
    command:
      - "-cmax_connections=3000"
    networks:
      antps-klaytn-networks:
        ipv4_address: 10.111.100.101

  backend:
    extends:
      file: ../explorer/backend.yml
      service: backend
    environment:
      DATABASE_URL: postgresql://postgres:0xantps@10.111.100.101:5432/blockscout
      ETHEREUM_JSONRPC_HTTP_URL: http://10.111.0.2:8551
      ETHEREUM_JSONRPC_TRACE_URL: http://10.111.0.2:8551
      ETHEREUM_JSONRPC_WS_URL: ws://10.111.0.2:9551
      ETHEREUM_JSONRPC_HTTP_INSECURE: 'true'
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      CHAIN_ID: '8216'
    ports:
      - '4000:4000'
    depends_on:
      - CN
      - EN
      - postgres
    networks:
      antps-klaytn-networks:
        ipv4_address: 10.111.101.100

  frontend:
    extends:
      file: ../explorer/frontend.yml
      service: frontend
    environment:
      NEXT_PUBLIC_API_HOST: '10.111.101.100:4000'
      NEXT_PUBLIC_APP_HOST: '10.111.101.101'
      NEXT_PUBLIC_API_BASE_PATH: '/'
    ports:
      - '3000:3000'
    depends_on:
      - CN
      - EN
      - postgres
    networks:
      antps-klaytn-networks:
        ipv4_address: 10.111.101.101

networks:
  antps-klaytn-networks:
    driver: bridge
    ipam:
      config:
        - subnet: 10.111.0.0/16