version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      - ./frontend.env
